spring:
    application:
        name: inventarios
    # La sección datasource se configurará con variables de entorno desde Docker Compose
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: public
    output:
        ansi:
            enabled: always
server:
    port: 8081
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /inventory-management/swagger-ui.html
        version: 1.0.0

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always